---
name: Validate Code

on: [push, pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version
      - name: Install commitlint
        run: npm install -g commitlint@latest @commitlint/config-conventional

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    needs: commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Validate code with eslint
        run: npx --no-install eslint ./src
      - name: Validate code with prettier
        run: npx --no-install prettier --check ./src
      - name: Run tests
        run: yarn test
